name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-06"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjgwZDdmOWEtYWVmNy00ZTE3LTlhYzctMmE3NDM2ZTliMTMyIiwidGVuYW50X2lkIjoiMjllZTMwZTQ5MGExYjFlYjc2MTM1OWUyMDQzNmZhYzFkZDAxOWU4YTE5MGMxZjFkOTMzNzI5ODJkOTMxNDEzYiIsImludGVybmFsX3NlY3JldCI6IjBkZjkwYzdiLWU4Y2QtNGVmZC05NTRmLTRjNmI2Mjc5OTFmYyJ9.lOCixvJP_9XnUKwUYWKeSC1M0Dv9ziRJRwz1RoU7zpI"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1